<?php
/**
 * AddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Seacommerce\Unit4\Multivers\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UNIT4 Multivers WebApi
 *
 * Unofficial specification of the the UNIT4 Multivers WebApi version 1.10.0 by Seacommerce.
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Seacommerce\Unit4\Multivers\Sdk;

/**
 * AddressTest Class Doc Comment
 *
 * @category    Class
 * @description Address
 * @package     Seacommerce\Unit4\Multivers\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Address"
     */
    public function testAddress()
    {
    }

    /**
     * Test attribute "addressGuid"
     */
    public function testPropertyAddressGuid()
    {
    }

    /**
     * Test attribute "addressId"
     */
    public function testPropertyAddressId()
    {
    }

    /**
     * Test attribute "addressType"
     */
    public function testPropertyAddressType()
    {
    }

    /**
     * Test attribute "canChange"
     */
    public function testPropertyCanChange()
    {
    }

    /**
     * Test attribute "cannotChangeReason"
     */
    public function testPropertyCannotChangeReason()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "contactPerson"
     */
    public function testPropertyContactPerson()
    {
    }

    /**
     * Test attribute "countryId"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "fullAddress"
     */
    public function testPropertyFullAddress()
    {
    }

    /**
     * Test attribute "languageId"
     */
    public function testPropertyLanguageId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "organizationId"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "street1"
     */
    public function testPropertyStreet1()
    {
    }

    /**
     * Test attribute "street2"
     */
    public function testPropertyStreet2()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "zipCode"
     */
    public function testPropertyZipCode()
    {
    }
}
