<?php
/**
 * CustomerInvoicePaymentInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Seacommerce\Unit4\Multivers\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UNIT4 Multivers WebApi
 *
 * Unofficial SDK for the UNIT4 Multivers WebApi version 1.10.0 (by Seacommerce).
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Seacommerce\Unit4\Multivers\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * CustomerInvoicePaymentInfoTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerInvoicePaymentInfo
 * @package     Seacommerce\Unit4\Multivers\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomerInvoicePaymentInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerInvoicePaymentInfo"
     */
    public function testCustomerInvoicePaymentInfo()
    {
    }

    /**
     * Test attribute "creditSqueezeAmount"
     */
    public function testPropertyCreditSqueezeAmount()
    {
    }

    /**
     * Test attribute "creditSqueezeAmountCur"
     */
    public function testPropertyCreditSqueezeAmountCur()
    {
    }

    /**
     * Test attribute "exchangeDifferenceAmount"
     */
    public function testPropertyExchangeDifferenceAmount()
    {
    }

    /**
     * Test attribute "fiscalYear"
     */
    public function testPropertyFiscalYear()
    {
    }

    /**
     * Test attribute "journalId"
     */
    public function testPropertyJournalId()
    {
    }

    /**
     * Test attribute "journalTransaction"
     */
    public function testPropertyJournalTransaction()
    {
    }

    /**
     * Test attribute "paidAmount"
     */
    public function testPropertyPaidAmount()
    {
    }

    /**
     * Test attribute "paidAmountCur"
     */
    public function testPropertyPaidAmountCur()
    {
    }

    /**
     * Test attribute "paymentDate"
     */
    public function testPropertyPaymentDate()
    {
    }

    /**
     * Test attribute "paymentDifferenceAmount"
     */
    public function testPropertyPaymentDifferenceAmount()
    {
    }

    /**
     * Test attribute "paymentDifferenceAmountCur"
     */
    public function testPropertyPaymentDifferenceAmountCur()
    {
    }

    /**
     * Test attribute "paymentRebateAmount"
     */
    public function testPropertyPaymentRebateAmount()
    {
    }

    /**
     * Test attribute "paymentRebateAmountCur"
     */
    public function testPropertyPaymentRebateAmountCur()
    {
    }
}
