<?php
/**
 * CustomerInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Seacommerce\Unit4\Multivers\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UNIT4 Multivers WebApi
 *
 * Unofficial specification of the the UNIT4 Multivers WebApi version 1.10.0 by Seacommerce.
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Seacommerce\Unit4\Multivers\Sdk;

/**
 * CustomerInfoTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerInfo
 * @package     Seacommerce\Unit4\Multivers\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomerInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerInfo"
     */
    public function testCustomerInfo()
    {
    }

    /**
     * Test attribute "accountManagerId"
     */
    public function testPropertyAccountManagerId()
    {
    }

    /**
     * Test attribute "applyOrderSurcharge"
     */
    public function testPropertyApplyOrderSurcharge()
    {
    }

    /**
     * Test attribute "businessNumber"
     */
    public function testPropertyBusinessNumber()
    {
    }

    /**
     * Test attribute "chargeVatTypeId"
     */
    public function testPropertyChargeVatTypeId()
    {
    }

    /**
     * Test attribute "cocCity"
     */
    public function testPropertyCocCity()
    {
    }

    /**
     * Test attribute "cocDate"
     */
    public function testPropertyCocDate()
    {
    }

    /**
     * Test attribute "cocRegistration"
     */
    public function testPropertyCocRegistration()
    {
    }

    /**
     * Test attribute "collectiveInvoiceSystemId"
     */
    public function testPropertyCollectiveInvoiceSystemId()
    {
    }

    /**
     * Test attribute "combineInvoicesForElectronicBanking"
     */
    public function testPropertyCombineInvoicesForElectronicBanking()
    {
    }

    /**
     * Test attribute "contactPerson"
     */
    public function testPropertyContactPerson()
    {
    }

    /**
     * Test attribute "creditLimit"
     */
    public function testPropertyCreditLimit()
    {
    }

    /**
     * Test attribute "creditSqueezeId"
     */
    public function testPropertyCreditSqueezeId()
    {
    }

    /**
     * Test attribute "currencyId"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "customerGroupId"
     */
    public function testPropertyCustomerGroupId()
    {
    }

    /**
     * Test attribute "customerOrganizationId"
     */
    public function testPropertyCustomerOrganizationId()
    {
    }

    /**
     * Test attribute "customerStateId"
     */
    public function testPropertyCustomerStateId()
    {
    }

    /**
     * Test attribute "dateChanged"
     */
    public function testPropertyDateChanged()
    {
    }

    /**
     * Test attribute "dateCreated"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "deliveryConditionId"
     */
    public function testPropertyDeliveryConditionId()
    {
    }

    /**
     * Test attribute "discountPercentage"
     */
    public function testPropertyDiscountPercentage()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "governmentDigitalId"
     */
    public function testPropertyGovernmentDigitalId()
    {
    }

    /**
     * Test attribute "homepage"
     */
    public function testPropertyHomepage()
    {
    }

    /**
     * Test attribute "includeVatOnOrderByDefault"
     */
    public function testPropertyIncludeVatOnOrderByDefault()
    {
    }

    /**
     * Test attribute "intrastatGoodsCodeId"
     */
    public function testPropertyIntrastatGoodsCodeId()
    {
    }

    /**
     * Test attribute "intrastatGoodsDistributionId"
     */
    public function testPropertyIntrastatGoodsDistributionId()
    {
    }

    /**
     * Test attribute "intrastatStatSystemId"
     */
    public function testPropertyIntrastatStatSystemId()
    {
    }

    /**
     * Test attribute "intrastatTrafficRegionId"
     */
    public function testPropertyIntrastatTrafficRegionId()
    {
    }

    /**
     * Test attribute "intrastatTransactionTypeId"
     */
    public function testPropertyIntrastatTransactionTypeId()
    {
    }

    /**
     * Test attribute "intrastatTransportTypeId"
     */
    public function testPropertyIntrastatTransportTypeId()
    {
    }

    /**
     * Test attribute "invoiceOnBehalfOfMembers"
     */
    public function testPropertyInvoiceOnBehalfOfMembers()
    {
    }

    /**
     * Test attribute "isDunForPayment"
     */
    public function testPropertyIsDunForPayment()
    {
    }

    /**
     * Test attribute "isInFactoring"
     */
    public function testPropertyIsInFactoring()
    {
    }

    /**
     * Test attribute "isPaymentRefRequired"
     */
    public function testPropertyIsPaymentRefRequired()
    {
    }

    /**
     * Test attribute "isPurchaseOrganization"
     */
    public function testPropertyIsPurchaseOrganization()
    {
    }

    /**
     * Test attribute "languageId"
     */
    public function testPropertyLanguageId()
    {
    }

    /**
     * Test attribute "mobilePhone"
     */
    public function testPropertyMobilePhone()
    {
    }

    /**
     * Test attribute "paymentConditionId"
     */
    public function testPropertyPaymentConditionId()
    {
    }

    /**
     * Test attribute "pricelistId"
     */
    public function testPropertyPricelistId()
    {
    }

    /**
     * Test attribute "printPurchaseDetails"
     */
    public function testPropertyPrintPurchaseDetails()
    {
    }

    /**
     * Test attribute "purchaseOrganizationId"
     */
    public function testPropertyPurchaseOrganizationId()
    {
    }

    /**
     * Test attribute "purchaseOrganizationMemberId"
     */
    public function testPropertyPurchaseOrganizationMemberId()
    {
    }

    /**
     * Test attribute "revenueAccountId"
     */
    public function testPropertyRevenueAccountId()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "usesUBLInvoice"
     */
    public function testPropertyUsesUBLInvoice()
    {
    }

    /**
     * Test attribute "vatNumber"
     */
    public function testPropertyVatNumber()
    {
    }

    /**
     * Test attribute "vatScenarioId"
     */
    public function testPropertyVatScenarioId()
    {
    }

    /**
     * Test attribute "vatVerificationDate"
     */
    public function testPropertyVatVerificationDate()
    {
    }
}
