<?php
/**
 * OrderLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Seacommerce\Unit4\Multivers\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UNIT4 Multivers WebApi
 *
 * Unofficial SDK for the UNIT4 Multivers WebApi version 1.10.0 (by Seacommerce).
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Seacommerce\Unit4\Multivers\Sdk;

/**
 * OrderLineTest Class Doc Comment
 *
 * @category    Class
 * @description OrderLine
 * @package     Seacommerce\Unit4\Multivers\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrderLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderLine"
     */
    public function testOrderLine()
    {
    }

    /**
     * Test attribute "accountId"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "autoCalculatePrice"
     */
    public function testPropertyAutoCalculatePrice()
    {
    }

    /**
     * Test attribute "autoUnmatchToPurchase"
     */
    public function testPropertyAutoUnmatchToPurchase()
    {
    }

    /**
     * Test attribute "canChange"
     */
    public function testPropertyCanChange()
    {
    }

    /**
     * Test attribute "cannotChangeReason"
     */
    public function testPropertyCannotChangeReason()
    {
    }

    /**
     * Test attribute "costCentreId"
     */
    public function testPropertyCostCentreId()
    {
    }

    /**
     * Test attribute "costUnitId"
     */
    public function testPropertyCostUnitId()
    {
    }

    /**
     * Test attribute "deliveryDate"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "discountAccountId"
     */
    public function testPropertyDiscountAccountId()
    {
    }

    /**
     * Test attribute "matchedToPurchase"
     */
    public function testPropertyMatchedToPurchase()
    {
    }

    /**
     * Test attribute "orderLineAmount"
     */
    public function testPropertyOrderLineAmount()
    {
    }

    /**
     * Test attribute "orderLineId"
     */
    public function testPropertyOrderLineId()
    {
    }

    /**
     * Test attribute "orderLineType"
     */
    public function testPropertyOrderLineType()
    {
    }

    /**
     * Test attribute "pickListText"
     */
    public function testPropertyPickListText()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "pricePer"
     */
    public function testPropertyPricePer()
    {
    }

    /**
     * Test attribute "productId"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "quantityBackorder"
     */
    public function testPropertyQuantityBackorder()
    {
    }

    /**
     * Test attribute "quantityDelivered"
     */
    public function testPropertyQuantityDelivered()
    {
    }

    /**
     * Test attribute "quantityOrdered"
     */
    public function testPropertyQuantityOrdered()
    {
    }

    /**
     * Test attribute "quantityScale"
     */
    public function testPropertyQuantityScale()
    {
    }

    /**
     * Test attribute "quantityToDeliver"
     */
    public function testPropertyQuantityToDeliver()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "vatCodeId"
     */
    public function testPropertyVatCodeId()
    {
    }

    /**
     * Test attribute "warehouseId"
     */
    public function testPropertyWarehouseId()
    {
    }
}
