<?php
/**
 * ProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Seacommerce\Unit4\Multivers\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UNIT4 Multivers WebApi
 *
 * Unofficial specification of the the UNIT4 Multivers WebApi version 1.10.0 by Seacommerce.
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Seacommerce\Unit4\Multivers\Sdk;

/**
 * ProductTest Class Doc Comment
 *
 * @category    Class
 * @description Product
 * @package     Seacommerce\Unit4\Multivers\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Product"
     */
    public function testProduct()
    {
    }

    /**
     * Test attribute "accountId"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "additionalUnits"
     */
    public function testPropertyAdditionalUnits()
    {
    }

    /**
     * Test attribute "canChange"
     */
    public function testPropertyCanChange()
    {
    }

    /**
     * Test attribute "cannotChangeReason"
     */
    public function testPropertyCannotChangeReason()
    {
    }

    /**
     * Test attribute "components"
     */
    public function testPropertyComponents()
    {
    }

    /**
     * Test attribute "constellationNotition"
     */
    public function testPropertyConstellationNotition()
    {
    }

    /**
     * Test attribute "coverageAccountId"
     */
    public function testPropertyCoverageAccountId()
    {
    }

    /**
     * Test attribute "currentStock"
     */
    public function testPropertyCurrentStock()
    {
    }

    /**
     * Test attribute "dateCreated"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "discountAccountId"
     */
    public function testPropertyDiscountAccountId()
    {
    }

    /**
     * Test attribute "eANCode"
     */
    public function testPropertyEANCode()
    {
    }

    /**
     * Test attribute "intrastatCode"
     */
    public function testPropertyIntrastatCode()
    {
    }

    /**
     * Test attribute "lastUpdate"
     */
    public function testPropertyLastUpdate()
    {
    }

    /**
     * Test attribute "margin"
     */
    public function testPropertyMargin()
    {
    }

    /**
     * Test attribute "maxStock"
     */
    public function testPropertyMaxStock()
    {
    }

    /**
     * Test attribute "minStock"
     */
    public function testPropertyMinStock()
    {
    }

    /**
     * Test attribute "pricePer"
     */
    public function testPropertyPricePer()
    {
    }

    /**
     * Test attribute "priceVatExcl"
     */
    public function testPropertyPriceVatExcl()
    {
    }

    /**
     * Test attribute "priceVatIncl"
     */
    public function testPropertyPriceVatIncl()
    {
    }

    /**
     * Test attribute "printOnInvoice"
     */
    public function testPropertyPrintOnInvoice()
    {
    }

    /**
     * Test attribute "printOnQuote"
     */
    public function testPropertyPrintOnQuote()
    {
    }

    /**
     * Test attribute "printOnShippingOrder"
     */
    public function testPropertyPrintOnShippingOrder()
    {
    }

    /**
     * Test attribute "printOnWarehouseOrder"
     */
    public function testPropertyPrintOnWarehouseOrder()
    {
    }

    /**
     * Test attribute "productDescriptions"
     */
    public function testPropertyProductDescriptions()
    {
    }

    /**
     * Test attribute "productDiscountGroupId"
     */
    public function testPropertyProductDiscountGroupId()
    {
    }

    /**
     * Test attribute "productGroupId"
     */
    public function testPropertyProductGroupId()
    {
    }

    /**
     * Test attribute "productId"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "productState"
     */
    public function testPropertyProductState()
    {
    }

    /**
     * Test attribute "productSuppliers"
     */
    public function testPropertyProductSuppliers()
    {
    }

    /**
     * Test attribute "productType"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "projectEntryType"
     */
    public function testPropertyProjectEntryType()
    {
    }

    /**
     * Test attribute "projectSurchargePerc"
     */
    public function testPropertyProjectSurchargePerc()
    {
    }

    /**
     * Test attribute "publishOnWeb"
     */
    public function testPropertyPublishOnWeb()
    {
    }

    /**
     * Test attribute "purchaseOrderCount"
     */
    public function testPropertyPurchaseOrderCount()
    {
    }

    /**
     * Test attribute "quantityScale"
     */
    public function testPropertyQuantityScale()
    {
    }

    /**
     * Test attribute "shortName"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "stocks"
     */
    public function testPropertyStocks()
    {
    }

    /**
     * Test attribute "stockTransactionCount"
     */
    public function testPropertyStockTransactionCount()
    {
    }

    /**
     * Test attribute "stockTransferPrice"
     */
    public function testPropertyStockTransferPrice()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "vatCodeId"
     */
    public function testPropertyVatCodeId()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }
}
