<?php
/**
 * StockTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Seacommerce\Unit4\Multivers\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UNIT4 Multivers WebApi
 *
 * Unofficial specification of the the UNIT4 Multivers WebApi version 1.10.0 by Seacommerce.
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Seacommerce\Unit4\Multivers\Sdk;

/**
 * StockTest Class Doc Comment
 *
 * @category    Class
 * @description Stock
 * @package     Seacommerce\Unit4\Multivers\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StockTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Stock"
     */
    public function testStock()
    {
    }

    /**
     * Test attribute "availableStock"
     */
    public function testPropertyAvailableStock()
    {
    }

    /**
     * Test attribute "canChange"
     */
    public function testPropertyCanChange()
    {
    }

    /**
     * Test attribute "cannotChangeReason"
     */
    public function testPropertyCannotChangeReason()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "economicalStock"
     */
    public function testPropertyEconomicalStock()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "maximumStock"
     */
    public function testPropertyMaximumStock()
    {
    }

    /**
     * Test attribute "minimumStock"
     */
    public function testPropertyMinimumStock()
    {
    }

    /**
     * Test attribute "quantityClearedForDelivery"
     */
    public function testPropertyQuantityClearedForDelivery()
    {
    }

    /**
     * Test attribute "quantityOrdered"
     */
    public function testPropertyQuantityOrdered()
    {
    }

    /**
     * Test attribute "quantityOrderedSales"
     */
    public function testPropertyQuantityOrderedSales()
    {
    }

    /**
     * Test attribute "quantityReserved"
     */
    public function testPropertyQuantityReserved()
    {
    }

    /**
     * Test attribute "quantityToDeliver"
     */
    public function testPropertyQuantityToDeliver()
    {
    }

    /**
     * Test attribute "technicalStock"
     */
    public function testPropertyTechnicalStock()
    {
    }

    /**
     * Test attribute "warehouseId"
     */
    public function testPropertyWarehouseId()
    {
    }
}
