<?php
/**
 * CustomTableApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Seacommerce\Unit4\Multivers\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UNIT4 Multivers WebApi
 *
 * Unofficial SDK for the UNIT4 Multivers WebApi version 1.10.0 (by Seacommerce).
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Seacommerce\Unit4\Multivers\Sdk;

use \Seacommerce\Unit4\Multivers\Sdk\Configuration;
use \Seacommerce\Unit4\Multivers\Sdk\ApiException;
use \Seacommerce\Unit4\Multivers\Sdk\ObjectSerializer;

/**
 * CustomTableApiTest Class Doc Comment
 *
 * @category Class
 * @package  Seacommerce\Unit4\Multivers\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomTableApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCustomTableByTableName
     *
     * Gets the specified CustomTable..
     *
     */
    public function testGetCustomTableByTableName()
    {
    }

    /**
     * Test case for updateCustomTableByTableName
     *
     * Updates the specified CustomTable.
     *
     */
    public function testUpdateCustomTableByTableName()
    {
    }
}
